# Generated by Django 4.2.27 on 2026-01-10 20:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название области"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("priority", models.IntegerField(default=1, verbose_name="Приоритет")),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50", max_length=7, verbose_name="Цвет"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Область знаний",
                "verbose_name_plural": "Области знаний",
            },
        ),
        migrations.CreateModel(
            name="AreaMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        default=3,
                        help_text="Релевантность узла для области (1 - низкая, 5 - высокая)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Релевантность",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.area",
                        verbose_name="Область знаний",
                    ),
                ),
            ],
            options={
                "verbose_name": "Принадлежность к области",
                "verbose_name_plural": "Принадлежности к областям",
            },
        ),
        migrations.CreateModel(
            name="DailyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата обзора"
                    ),
                ),
                ("insights", models.TextField(blank=True, verbose_name="Инсайты дня")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневный обзор",
                "verbose_name_plural": "Ежедневные обзоры",
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="InformationNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CAPTURED", "Захвачено"),
                            ("ORGANIZED", "Организовано"),
                            ("DISTILLED", "Перегнано"),
                            ("EXPRESSED", "Выражено"),
                            ("ARCHIVED", "Архивировано"),
                        ],
                        default="CAPTURED",
                        max_length=20,
                        verbose_name="Этап обработки",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("ATOMIC", "Атомарная идея"),
                            ("CONCEPT", "Концепция"),
                            ("OBSERVATION", "Наблюдение"),
                            ("QUESTION", "Вопрос"),
                            ("HYPOTHESIS", "Гипотеза"),
                            ("SUMMARY", "Резюме"),
                            ("PROJECT_NOTE", "Заметка проекта"),
                        ],
                        default="ATOMIC",
                        max_length=20,
                        verbose_name="Тип узла",
                    ),
                ),
                (
                    "atomicity_score",
                    models.IntegerField(
                        default=1,
                        help_text="Насколько атомарна идея (1 - сложная, 10 - простая и законченная)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка атомарности",
                    ),
                ),
                (
                    "clarity_score",
                    models.IntegerField(
                        default=1,
                        help_text="Насколько ясно изложено (1 - сыро, 10 - кристально понятно)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка ясности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "last_reviewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний обзор"
                    ),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nodes",
                        through="collector.AreaMembership",
                        to="collector.area",
                        verbose_name="Области знаний",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информационный узел",
                "verbose_name_plural": "Информационные узлы",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тега"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#808080", max_length=7, verbose_name="Цвет"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="collector.tag",
                        verbose_name="Родительский тег",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("SOURCE_PROCESSING", "Обработка источника"),
                            ("NODE_CREATION", "Создание узла"),
                            ("OBSERVATION", "Наблюдение под микроскопом"),
                            ("RESEARCH_PAPER", "Научная статья"),
                            ("LITERATURE_REVIEW", "Обзор литературы"),
                        ],
                        max_length=50,
                        verbose_name="Тип шаблона",
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        default=dict,
                        help_text="Структура шаблона в формате JSON (поля, разделы)",
                        verbose_name="Структура шаблона",
                    ),
                ),
                (
                    "default_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collector.area",
                        verbose_name="Область по умолчанию",
                    ),
                ),
                (
                    "default_tags",
                    models.ManyToManyField(
                        blank=True, to="collector.tag", verbose_name="Теги по умолчанию"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Шаблоны",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=2000, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("WEB", "Веб-страница"),
                            ("YOUTUBE", "YouTube"),
                            ("BOOK", "Книга"),
                            ("ARTICLE", "Научная статья"),
                            ("MICROSCOPE", "Наблюдение под микроскопом"),
                            ("COURSE", "Курс/лекция"),
                            ("IDEA", "Собственная идея"),
                            ("OTHER", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Тип источника",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата сохранения"
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(blank=True, verbose_name="Исходный контент"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник информации",
                "verbose_name_plural": "Источники информации",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Название проекта"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Планирование"),
                            ("ACTIVE", "Активный"),
                            ("PAUSED", "Приостановлен"),
                            ("COMPLETED", "Завершен"),
                            ("ARCHIVED", "Архивирован"),
                        ],
                        default="PLANNING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True, to="collector.area", verbose_name="Области знаний"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="collector.tag", verbose_name="Теги"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="ProcessingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_stage",
                    models.CharField(
                        choices=[
                            ("CAPTURED", "Захвачено"),
                            ("ORGANIZED", "Организовано"),
                            ("DISTILLED", "Перегнано"),
                            ("EXPRESSED", "Выражено"),
                            ("ARCHIVED", "Архивировано"),
                        ],
                        max_length=20,
                        verbose_name="Предыдущий этап",
                    ),
                ),
                (
                    "new_stage",
                    models.CharField(
                        choices=[
                            ("CAPTURED", "Захвачено"),
                            ("ORGANIZED", "Организовано"),
                            ("DISTILLED", "Перегнано"),
                            ("EXPRESSED", "Выражено"),
                            ("ARCHIVED", "Архивировано"),
                        ],
                        max_length=20,
                        verbose_name="Новый этап",
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        default=list,
                        help_text="Список выполненных действий в формате JSON",
                        verbose_name="Выполненные действия",
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        help_text="Время в минутах, потраченное на обработку",
                        verbose_name="Затраченное время (мин)",
                    ),
                ),
                (
                    "insights_gained",
                    models.TextField(blank=True, verbose_name="Полученные инсайты"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата сессии"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="collector.informationnode",
                        verbose_name="Информационный узел",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия обработки",
                "verbose_name_plural": "Сессии обработки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="informationnode",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="nodes",
                to="collector.source",
                verbose_name="Источники",
            ),
        ),
        migrations.AddField(
            model_name="informationnode",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="nodes",
                to="collector.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddField(
            model_name="informationnode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("POCKET", "Pocket"),
                            ("READWISE", "Readwise"),
                            ("YOUTUBE", "YouTube History"),
                            ("BOOKMARKS", "Браузерные закладки"),
                            ("OBSIDIAN", "Obsidian"),
                            ("NOTION", "Notion"),
                        ],
                        max_length=20,
                        verbose_name="Тип источника",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="imports/",
                        verbose_name="Файл для импорта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDING", max_length=20, verbose_name="Статус"
                    ),
                ),
                (
                    "items_processed",
                    models.IntegerField(default=0, verbose_name="Обработано элементов"),
                ),
                (
                    "items_total",
                    models.IntegerField(default=0, verbose_name="Всего элементов"),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Ошибки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача импорта",
                "verbose_name_plural": "Задачи импорта",
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(max_length=50, verbose_name="Тип метрики"),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время записи"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика дашборда",
                "verbose_name_plural": "Метрики дашборда",
            },
        ),
        migrations.AddField(
            model_name="areamembership",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="collector.informationnode",
                verbose_name="Информационный узел",
            ),
        ),
        migrations.CreateModel(
            name="ProjectContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Как узел используется в проекте",
                        max_length=100,
                        verbose_name="Роль узла",
                    ),
                ),
                (
                    "importance",
                    models.IntegerField(
                        default=3,
                        help_text="Важность узла для проекта (1 - низкая, 5 - критическая)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Важность",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.informationnode",
                        verbose_name="Информационный узел",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вклад в проект",
                "verbose_name_plural": "Вклады в проекты",
                "unique_together": {("node", "project")},
            },
        ),
        migrations.CreateModel(
            name="NodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recall_score",
                    models.IntegerField(
                        choices=[
                            (1, "Не вспомнил"),
                            (2, "С трудом вспомнил"),
                            (3, "Вспомнил с подсказками"),
                            (4, "Вспомнил легко"),
                            (5, "Знаю отлично"),
                        ],
                        verbose_name="Оценка вспоминания",
                    ),
                ),
                (
                    "new_connections",
                    models.TextField(
                        blank=True,
                        help_text="Новые связи, возникшие при повторении",
                        verbose_name="Новые связи",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время повторения"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.informationnode",
                        verbose_name="Информационный узел",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.dailyreview",
                        verbose_name="Ежедневный обзор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Повторение узла",
                "verbose_name_plural": "Повторения узлов",
                "unique_together": {("review", "node")},
            },
        ),
        migrations.CreateModel(
            name="NodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("RELATES", "Относится к"),
                            ("SUPPORTS", "Подтверждает"),
                            ("CONTRADICTS", "Противоречит"),
                            ("DEVELOPS", "Развивает"),
                            ("ANSWERS", "Отвечает на"),
                            ("CITES", "Цитирует"),
                            ("EXAMPLE", "Пример для"),
                            ("APPLICATION", "Применение"),
                        ],
                        max_length=20,
                        verbose_name="Тип связи",
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        default=1,
                        help_text="Сила связи (1 - слабая, 5 - очень сильная)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Сила связи",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание связи"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="collector.informationnode",
                        verbose_name="Исходный узел",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="collector.informationnode",
                        verbose_name="Целевой узел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь между узлами",
                "verbose_name_plural": "Связи между узлами",
                "unique_together": {("from_node", "to_node", "link_type")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="areamembership",
            unique_together={("node", "area")},
        ),
    ]
