# Generated by Django 4.2.27 on 2026-01-10 03:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название метрики"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код метрики")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Питание"),
                            ("activity", "Активность"),
                            ("intellect", "Интеллект"),
                            ("body", "Тело"),
                            ("strength", "Силовые"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kcal", "ккал"),
                            ("g", "г"),
                            ("l", "л"),
                            ("hours", "ч"),
                            ("steps", "шагов"),
                            ("kg", "кг"),
                            ("%", "%"),
                            ("count", "шт"),
                            ("pages", "стр"),
                            ("minutes", "мин"),
                        ],
                        max_length=20,
                        verbose_name="Единица измерения",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Тип метрики",
                "verbose_name_plural": "Типы метрик",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ForceMajeure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="Причина")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="force_majeures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Форс-мажор",
                "verbose_name_plural": "Форс-мажоры",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("strength", "Силовая"),
                            ("cardio", "Кардио"),
                            ("flexibility", "Растяжка"),
                            ("mixed", "Смешанная"),
                        ],
                        max_length=20,
                        verbose_name="Тип тренировки",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Длительность (мин)"),
                ),
                (
                    "intensity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Интенсивность (1-10)",
                    ),
                ),
                (
                    "exercises",
                    models.TextField(verbose_name="Упражнения (JSON или текст)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="tracker_tra_user_id_b639ae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("min", "Минимум"),
                            ("max", "Максимум"),
                            ("exact", "Точное значение"),
                        ],
                        max_length=10,
                        verbose_name="Тип норматива",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Значение норматива",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="tracker.metrictype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Норматив метрики",
                "verbose_name_plural": "Нормативы метрик",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["user", "metric_type", "-valid_from"],
                        name="tracker_met_user_id_e0ed17_idx",
                    )
                ],
                "unique_together": {("user", "metric_type", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значение"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_values",
                        to="tracker.metrictype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневная метрика",
                "verbose_name_plural": "Ежедневные метрики",
                "ordering": ["-date", "metric_type__order"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="tracker_dai_user_id_bd6b5f_idx"
                    ),
                    models.Index(fields=["date"], name="tracker_dai_date_df5b5a_idx"),
                    models.Index(
                        fields=["user", "-date", "metric_type"],
                        name="tracker_dai_user_id_ebdc9e_idx",
                    ),
                ],
                "unique_together": {("user", "date", "metric_type")},
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата")),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "fat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="% жира",
                    ),
                ),
                (
                    "visceral_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Висцеральный жир",
                    ),
                ),
                (
                    "muscle_mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Мышечная масса (кг)",
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Грудь (см)",
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Талия (см)",
                    ),
                ),
                (
                    "hips",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Бедра (см)",
                    ),
                ),
                (
                    "biceps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Бицепс (см)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Замер тела",
                "verbose_name_plural": "Замеры тела",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="tracker_bod_user_id_00c001_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
